language: generic 

sudo: required
services:
    - docker

before_install:
    - docker build -t nherzog2020/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true nherzog2020/docker-react npm run test